"""
kagome_hva.py
=============
Utilities for the Task 1 Proof-of-Concept:

    "Show that adding layers of Heisenberg (eSWAP) gates to the ansatz,
     PROGRESSIVELY, (1) brings the state closer to a Quantum Spin Liquid and
     (2) reaches the benchmark energy WITHOUT Hamiltonian calibration."

This module COMPLEMENTS `kagome_common.py` (which reproduces the advisor's paper
with the RealAmplitudes ansatz + J'≈2 calibration). Here the Hamiltonian is NOT
calibrated: J = 1 uniform on every bond (the H of Sec. 3.1 of the paper,
not H_pert).

Contents:
  - heisenberg_gate / heis_matrix : the exchange gate exp(-iθ(XX+YY+ZZ)/4)
  - total_spin_operator           : S^2_total = Σ_i<j S_i·S_j (+3N/4), QSL-ness metric
  - HVASimulator                  : fast statevector engine (tensor contraction) for
                                    the HVA layer sweep without re-synthesizing circuits
  - run_hva_sweep                 : "progressive" sweep with layer-by-layer warm start
  - build_hva_circuit             : the equivalent Qiskit circuit (for drawing / hardware)

Energy convention (the paper's ×4): H = Σ_(i,j) (X_iX_j + Y_iY_j + Z_iZ_j).
With it, a singlet on a bond scores -3 and a triplet +1.

Requires: qiskit>=2.0, qiskit-aer, scipy, numpy, networkx
"""

from __future__ import annotations
import numpy as np
from scipy.optimize import minimize
from scipy.sparse.linalg import eigsh

from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.quantum_info import SparsePauliOp, Statevector
from qiskit.circuit.library import PauliEvolutionGate


# --------------------------------------------------------------------------
# 1. The Heisenberg / eSWAP gate
# --------------------------------------------------------------------------
def heisenberg_gate(theta):
    """
    Two-qubit gate generated by the Heisenberg exchange term:

        U_H(θ) = exp( -i θ (XX + YY + ZZ) / 4 )

    Implemented with PauliEvolutionGate. Since SWAP = (I + XX + YY + ZZ)/2, one has
    U_H(θ) = e^{iθ/4} · eSWAP(θ),  with  eSWAP(θ)=cos(θ/2)I − i sin(θ/2)SWAP.
    Being generated by (XX+YY+ZZ) it commutes with S^2_total and S^z_total: it
    preserves the total-spin sector. Returns a `Gate` to insert into a circuit.
    """
    op = SparsePauliOp.from_list([("XX", 1.0), ("YY", 1.0), ("ZZ", 1.0)])
    # PauliEvolutionGate(op, time=t) = exp(-i t op). We want exp(-iθ(XX+YY+ZZ)/4)
    # => time = θ/4.
    return PauliEvolutionGate(op, time=theta / 4.0)


def heis_matrix(theta):
    """
    Analytic 4x4 matrix of U_H(θ) in the {|00>,|01>,|10>,|11>} basis.
    (XX+YY+ZZ) has eigenvalue +1 on the triplet subspace and -3 on the singlet,
    so U_H applies phase e^{-iθ/4} to the triplet and e^{+3iθ/4} to the singlet.
    Used by the fast statevector engine.
    """
    a = np.exp(-1j * theta / 4.0)   # triplet phase
    s = np.exp(+3j * theta / 4.0)   # singlet phase
    G = np.zeros((4, 4), dtype=complex)
    G[0, 0] = a                      # |00> triplet
    G[3, 3] = a                      # |11> triplet
    p = 0.5 * (a + s)                # {|01>,|10>} block
    q = 0.5 * (a - s)
    G[1, 1] = p; G[2, 2] = p; G[1, 2] = q; G[2, 1] = q
    return G


# --------------------------------------------------------------------------
# 2. Operators: Hamiltonian (J=1), S^2_total, bond energies
# --------------------------------------------------------------------------
def heisenberg_hamiltonian(n, edges, weights=None):
    """H = Σ_(i,j) w_ij (X_iX_j+Y_iY_j+Z_iZ_j) as a SparsePauliOp (little-endian order)."""
    if weights is None:
        weights = [1.0] * len(edges)
    terms = []
    for (i, j), w in zip(edges, weights):
        for P in "XYZ":
            lab = ["I"] * n
            lab[n - 1 - i] = P
            lab[n - 1 - j] = P
            terms.append(("".join(lab), float(w)))
    return SparsePauliOp.from_list(terms).simplify()


def total_spin_operator(n):
    """
    S^2_total = (Σ_i S_i)^2 = 3N/4 · I + 2 Σ_{i<j} S_i·S_j,  with S_i·S_j=(XX+YY+ZZ)/4.
    Eigenvalue S(S+1): singlet S=0 -> 0 ; doublet S=1/2 -> 0.75 ; triplet S=1 -> 2.
    This is the primary "QSL-ness" metric: it measures whether the state lives in the
    correct spin sector (the RealAmplitudes ansatz breaks this symmetry).
    """
    terms = [("I" * n, 3 * n / 4.0)]
    for i in range(n):
        for j in range(i + 1, n):
            for P in "XYZ":
                lab = ["I"] * n
                lab[n - 1 - i] = P
                lab[n - 1 - j] = P
                terms.append(("".join(lab), 0.5))   # 2 * (1/4)
    return SparsePauliOp.from_list(terms).simplify()


def exact_ground_state(n, edges, weights=None):
    """Lowest eigenvalue and eigenvector via sparse Lanczos. Returns (E0, psi0)."""
    H = heisenberg_hamiltonian(n, edges, weights).to_matrix(sparse=True)
    w, v = eigsh(H.tocsr(), k=1, which="SA")
    return float(w[0]), v[:, 0]


# --------------------------------------------------------------------------
# 3. Fast statevector engine (tensor contraction) for the HVA sweep
# --------------------------------------------------------------------------
# 2-qubit Paulis (for the bond energies)
_X = np.array([[0, 1], [1, 0]], complex)
_Y = np.array([[0, -1j], [1j, 0]], complex)
_Z = np.array([[1, 0], [0, -1]], complex)
_XX, _YY, _ZZ = np.kron(_X, _X), np.kron(_Y, _Y), np.kron(_Z, _Z)
_BOND = _XX + _YY + _ZZ     # bond-energy generator


class HVASimulator:
    """
    Prepares |dimer⟩ and applies layers of Heisenberg gates via tensor contraction
    (numpy), avoiding circuit re-synthesis at every VQE evaluation.
    Qubit convention identical to Qiskit: qubit q maps to axis (n-1-q) after
    `reshape((2,)*n)` in C order (validated against qiskit.quantum_info.Statevector).
    """

    def __init__(self, n, edges, dimers, weights=None):
        self.n = n
        self.edges = [tuple(e) for e in edges]
        self.dimers = [tuple(d) for d in dimers]
        H = heisenberg_hamiltonian(n, edges, weights)
        self.H_sparse = H.to_matrix(sparse=True).tocsr()
        self.S2_sparse = total_spin_operator(n).to_matrix(sparse=True).tocsr()
        self.psi0 = self._dimer_state().reshape((2,) * n)
        self.n_params_per_layer = len(self.edges)

    # ---- initial state: product of singlets (dimer cover) ----
    def _dimer_state(self):
        qc = QuantumCircuit(self.n)
        for a, b in self.dimers:
            # prepares the singlet (|01>-|10>)/√2 on (a,b); unpaired qubits
            # (spinons) stay in |0>  -> they contribute S=1/2 (relevant for odd N).
            qc.h(a); qc.x(b); qc.cx(a, b); qc.z(a)
        return Statevector(qc).data

    # ---- apply a 2-qubit gate (4x4 matrix) ----
    def _apply2(self, psi, G, a, b):
        axa, axb = self.n - 1 - a, self.n - 1 - b
        psi = np.moveaxis(psi, [axa, axb], [0, 1])
        sh = psi.shape
        psi = (G @ psi.reshape(4, -1)).reshape(sh)
        return np.moveaxis(psi, [0, 1], [axa, axb])

    # ---- build the HVA statevector for parameters x ----
    def statevector(self, x, reps):
        psi = self.psi0.copy()
        k = 0
        for _ in range(reps):
            for (i, j) in self.edges:
                psi = self._apply2(psi, heis_matrix(x[k]), i, j)
                k += 1
        return psi.reshape(-1)

    # ---- observables ----
    def energy(self, x, reps):
        sv = self.statevector(x, reps)
        return float(np.real(np.vdot(sv, self.H_sparse @ sv)))

    def s2(self, sv):
        return float(np.real(np.vdot(sv, self.S2_sparse @ sv)))

    def bond_energies(self, sv):
        """Returns {(i,j): ⟨X_iX_j+Y_iY_j+Z_iZ_j⟩} for every bond (bond-energy map)."""
        psiT = sv.reshape((2,) * self.n)
        out = {}
        for (i, j) in self.edges:
            b = self._apply2(psiT, _BOND, i, j).reshape(-1)
            out[(i, j)] = float(np.real(np.vdot(sv, b)))
        return out

    # ---- energy + analytic gradient (adjoint method / backprop) ----
    def _gate_list(self, x, reps):
        gates, k = [], 0
        for _ in range(reps):
            for (i, j) in self.edges:
                gates.append((i, j, x[k])); k += 1
        return gates

    def energy_and_grad(self, x, reps):
        """
        Returns (E, grad) with E=⟨ψ(x)|H|ψ(x)⟩ and grad=∂E/∂x via adjoint
        differentiation: since U_k(θ)=exp(-iθ M_k) with M_k=(X_aX_b+Y_aY_b+Z_aZ_b)/4,
        we have ∂U_k/∂θ = -i M_k U_k, and the WHOLE gradient comes out of one forward
        and one backward pass (cost ≈ 3 energy evaluations, independent of #params),
        instead of one evaluation per parameter as in finite differences.
        """
        gates = self._gate_list(x, reps)
        M = _BOND / 4.0
        # forward
        psiT = self.psi0.copy()
        for (i, j, th) in gates:
            psiT = self._apply2(psiT, heis_matrix(th), i, j)
        psi = psiT.reshape(-1)
        E = float(np.real(np.vdot(psi, self.H_sparse @ psi)))
        # backward
        bT = (self.H_sparse @ psi).reshape((2,) * self.n)     # |b_N> = H|ψ_N>
        grad = np.empty(len(gates))
        for idx in range(len(gates) - 1, -1, -1):
            i, j, th = gates[idx]
            Mp = self._apply2(psiT, M, i, j).reshape(-1)       # M_k |ψ_k>
            grad[idx] = 2.0 * np.real(-1j * np.vdot(bT.reshape(-1), Mp))
            psiT = self._apply2(psiT, heis_matrix(-th), i, j)  # uncompute: U_k† |ψ_k>
            bT = self._apply2(bT, heis_matrix(-th), i, j)      # U_k† |b_k>
        return E, grad


def run_hva_sweep_grad(sim, E_exact, psi_exact=None, max_reps=6, n_random=2,
                       maxiter=300, seed=0, verbose=True):
    """
    Same as run_hva_sweep but with L-BFGS-B + analytic gradient (much better
    convergence per evaluation). Layer-by-layer warm start + n_random restarts.
    """
    rng = np.random.default_rng(seed)
    npl = sim.n_params_per_layer
    results = []

    sv0 = sim.psi0.reshape(-1)
    e0 = float(np.real(np.vdot(sv0, sim.H_sparse @ sv0)))
    results.append(dict(reps=0, n_params=0, energy=e0,
                        err_pct=abs(e0 - E_exact) / abs(E_exact) * 100,
                        s2=sim.s2(sv0),
                        fidelity=(abs(np.vdot(psi_exact, sv0))**2 if psi_exact is not None else np.nan),
                        x=np.array([])))
    if verbose:
        print(f"reps=0  static dimers       E={e0:8.3f}  err={results[-1]['err_pct']:6.2f}%  <S^2>={results[-1]['s2']:.4f}")

    prev = np.array([])
    for reps in range(1, max_reps + 1):
        npar = reps * npl
        inits = []
        if prev.size:
            inits.append(np.concatenate([prev, rng.uniform(-0.05, 0.05, npl)]))
        for _ in range(n_random):
            inits.append(rng.uniform(-0.5, 0.5, npar))

        best, bestx = np.inf, None
        for x0 in inits:
            res = minimize(lambda z: sim.energy_and_grad(z, reps), x0, jac=True,
                           method="L-BFGS-B", options={"maxiter": maxiter})
            if res.fun < best:
                best, bestx = res.fun, res.x
        prev = bestx

        sv = sim.statevector(bestx, reps)
        rec = dict(reps=reps, n_params=npar, energy=best,
                   err_pct=abs(best - E_exact) / abs(E_exact) * 100,
                   s2=sim.s2(sv),
                   fidelity=(abs(np.vdot(psi_exact, sv))**2 if psi_exact is not None else np.nan),
                   x=bestx)
        results.append(rec)
        if verbose:
            fid = "" if psi_exact is None else f"  fid={rec['fidelity']:.4f}"
            print(f"reps={reps}  params={npar:3d}          E={best:8.3f}  "
                  f"err={rec['err_pct']:6.2f}%  <S^2>={rec['s2']:.4f}{fid}")
    return results


# --------------------------------------------------------------------------
# 4. "Progressive" layer sweep with warm start
# --------------------------------------------------------------------------
def run_hva_sweep(sim, E_exact, psi_exact=None, max_reps=4, n_random=2,
                  maxiter=600, rhobeg=0.4, seed=0, verbose=True):
    """
    Optimizes the HVA for reps = 1..max_reps. Layer-by-layer warm-start strategy:
    the best solution of `reps` initializes `reps+1` (new parameters ≈ 0, i.e. the
    new layer starts as the identity). `n_random` random restarts are added.

    Returns a list of dicts with: reps, n_params, energy, err_pct, s2, fidelity, x.
    (reps=0 = static dimer state, unoptimized.)
    """
    rng = np.random.default_rng(seed)
    npl = sim.n_params_per_layer
    results = []

    # reps = 0 : static dimers ("no layers" reference)
    sv0 = sim.psi0.reshape(-1)
    e0 = float(np.real(np.vdot(sv0, sim.H_sparse @ sv0)))
    results.append(dict(reps=0, n_params=0, energy=e0,
                        err_pct=abs(e0 - E_exact) / abs(E_exact) * 100,
                        s2=sim.s2(sv0),
                        fidelity=(abs(np.vdot(psi_exact, sv0))**2 if psi_exact is not None else np.nan),
                        x=np.array([])))
    if verbose:
        r = results[-1]
        print(f"reps=0  static dimers       E={e0:8.3f}  err={r['err_pct']:6.2f}%  <S^2>={r['s2']:.4f}")

    prev = np.array([])
    for reps in range(1, max_reps + 1):
        npar = reps * npl
        inits = []
        if prev.size:                       # warm start: new layer ≈ identity
            inits.append(np.concatenate([prev, rng.uniform(-0.1, 0.1, npl)]))
        for _ in range(n_random):
            inits.append(rng.uniform(-rhobeg, rhobeg, npar))

        best, bestx = np.inf, None
        for x0 in inits:
            res = minimize(lambda z: sim.energy(z, reps), x0, method="COBYLA",
                           options={"maxiter": maxiter, "rhobeg": rhobeg})
            if res.fun < best:
                best, bestx = res.fun, res.x
        prev = bestx

        sv = sim.statevector(bestx, reps)
        rec = dict(reps=reps, n_params=npar, energy=best,
                   err_pct=abs(best - E_exact) / abs(E_exact) * 100,
                   s2=sim.s2(sv),
                   fidelity=(abs(np.vdot(psi_exact, sv))**2 if psi_exact is not None else np.nan),
                   x=bestx)
        results.append(rec)
        if verbose:
            fid = "" if psi_exact is None else f"  fid={rec['fidelity']:.4f}"
            print(f"reps={reps}  params={npar:3d}          E={best:8.3f}  "
                  f"err={rec['err_pct']:6.2f}%  <S^2>={rec['s2']:.4f}{fid}")
    return results


# --------------------------------------------------------------------------
# 5. Equivalent Qiskit circuit (for drawing / running on hardware)
# --------------------------------------------------------------------------
def build_hva_circuit(n, edges, dimers, reps):
    """
    Qiskit circuit of the HVA: dimer preparation + `reps` layers of Heisenberg
    gates (one per bond, one parameter per bond per layer). Equivalent to the fast
    engine; useful for drawing it or transpiling it to IBM hardware.
    """
    qc = QuantumCircuit(n)
    for a, b in dimers:
        qc.h(a); qc.x(b); qc.cx(a, b); qc.z(a)
    qc.barrier()
    P = ParameterVector("θ", reps * len(edges))
    k = 0
    for _ in range(reps):
        for (i, j) in edges:
            qc.append(heisenberg_gate(P[k]), [i, j])
            k += 1
    return qc, P


# --------------------------------------------------------------------------
# 6. SYMMETRIC HVA variant: fewer parameters (θ shared per edge class)
# --------------------------------------------------------------------------
# The "full" HVA has one θ per bond per layer (e.g. 30 params/layer on 19 sites).
# The symmetric variant groups the bonds into classes via edge coloring (each class
# = a matching of mutually disjoint bonds, Trotter-like) and uses ONE θ per class
# per layer (e.g. ~5 params/layer). Far fewer parameters => better-conditioned and
# cheaper optimization, and it is the physically motivated form (à la Kattemölle-van
# Wezel).
#
# The derivative w.r.t. a shared θ is the SUM of the per-gate derivatives (chain
# rule), so the already-validated adjoint gradient is reused EXACTLY: we just
# accumulate grad at the reduced parameter index instead of per gate.

def edge_color_classes(edges):
    """
    Colors the graph's edges (each color = a set of mutually disjoint bonds). Returns
    (colors, ncol) where colors[k] is the color of bond edges[k] and ncol the number
    of classes.
    """
    import networkx as nx
    el = [tuple(e) for e in edges]
    G = nx.Graph(); G.add_edges_from(el)
    coloring = nx.coloring.greedy_color(nx.line_graph(G), strategy="largest_first")
    norm = lambda e: tuple(sorted(e))
    cmap = {norm(k): v for k, v in coloring.items()}
    colors = [cmap[norm(e)] for e in el]
    return colors, (max(colors) + 1)


def symmetric_schedule(sim, reps, colors, ncol):
    """
    Gate list [(i, j, pidx)] for the symmetric HVA: in layer r, bond edges[k] uses
    the reduced parameter pidx = r*ncol + colors[k]. n_params = reps*ncol.
    The gate order is identical to the full HVA (forward/adjoint consistency).
    """
    sched = []
    for r in range(reps):
        for k, (i, j) in enumerate(sim.edges):
            sched.append((i, j, r * ncol + colors[k]))
    return sched, reps * ncol


def statevector_schedule(sim, theta, schedule):
    """Statevector obtained by applying the `schedule` gates with angles theta[pidx]."""
    psi = sim.psi0.copy()
    for (i, j, p) in schedule:
        psi = sim._apply2(psi, heis_matrix(theta[p]), i, j)
    return psi.reshape(-1)


def energy_and_grad_schedule(sim, theta, schedule, n_params):
    """
    (E, grad) for a generic `schedule` whose parameters may be SHARED across gates.
    Same adjoint method as HVASimulator.energy_and_grad, but the gradient is
    accumulated (+=) at the reduced parameter index:
    dE/dθ_p = Σ_{gates with pidx=p} ∂E/∂θ_g.
    """
    M = _BOND / 4.0
    psiT = sim.psi0.copy()
    for (i, j, p) in schedule:
        psiT = sim._apply2(psiT, heis_matrix(theta[p]), i, j)
    psi = psiT.reshape(-1)
    E = float(np.real(np.vdot(psi, sim.H_sparse @ psi)))
    bT = (sim.H_sparse @ psi).reshape((2,) * sim.n)
    grad = np.zeros(n_params)
    for (i, j, p) in reversed(schedule):
        Mp = sim._apply2(psiT, M, i, j).reshape(-1)
        grad[p] += 2.0 * np.real(-1j * np.vdot(bT.reshape(-1), Mp))
        psiT = sim._apply2(psiT, heis_matrix(-theta[p]), i, j)
        bT = sim._apply2(bT, heis_matrix(-theta[p]), i, j)
    return E, grad


def run_hva_sweep_symmetric(sim, E_exact, psi_exact=None, max_reps=6, n_random=2,
                            maxiter=300, seed=0, verbose=True):
    """
    Progressive sweep of the SYMMETRIC HVA (θ shared per edge class) with
    L-BFGS-B + analytic gradient and layer-by-layer warm start. Returns the same
    result structure as run_hva_sweep_grad, plus 'n_classes'.
    """
    rng = np.random.default_rng(seed)
    colors, ncol = edge_color_classes(sim.edges)
    results = []

    sv0 = sim.psi0.reshape(-1)
    e0 = float(np.real(np.vdot(sv0, sim.H_sparse @ sv0)))
    results.append(dict(reps=0, n_params=0, n_classes=ncol, energy=e0,
                        err_pct=abs(e0 - E_exact) / abs(E_exact) * 100, s2=sim.s2(sv0),
                        fidelity=(abs(np.vdot(psi_exact, sv0))**2 if psi_exact is not None else np.nan),
                        x=np.array([])))
    if verbose:
        print(f"[symmetric HVA: {ncol} edge classes -> {ncol} params/layer "
              f"(vs {sim.n_params_per_layer} in the full HVA)]")
        print(f"reps=0  static dimers       E={e0:8.3f}  err={results[-1]['err_pct']:6.2f}%  <S^2>={results[-1]['s2']:.4f}")

    prev = np.array([])
    for reps in range(1, max_reps + 1):
        sched, npar = symmetric_schedule(sim, reps, colors, ncol)
        inits = []
        if prev.size:
            inits.append(np.concatenate([prev, rng.uniform(-0.05, 0.05, ncol)]))
        for _ in range(n_random):
            inits.append(rng.uniform(-0.5, 0.5, npar))

        best, bestx = np.inf, None
        for x0 in inits:
            res = minimize(lambda z: energy_and_grad_schedule(sim, z, sched, npar), x0,
                           jac=True, method="L-BFGS-B", options={"maxiter": maxiter})
            if res.fun < best:
                best, bestx = res.fun, res.x
        prev = bestx

        sv = statevector_schedule(sim, bestx, sched)
        rec = dict(reps=reps, n_params=npar, n_classes=ncol, energy=best,
                   err_pct=abs(best - E_exact) / abs(E_exact) * 100, s2=sim.s2(sv),
                   fidelity=(abs(np.vdot(psi_exact, sv))**2 if psi_exact is not None else np.nan),
                   x=bestx)
        results.append(rec)
        if verbose:
            fid = "" if psi_exact is None else f"  fid={rec['fidelity']:.4f}"
            print(f"reps={reps}  params={npar:3d}          E={best:8.3f}  "
                  f"err={rec['err_pct']:6.2f}%  <S^2>={rec['s2']:.4f}{fid}")
    return results


# --------------------------------------------------------------------------
# 7. Hybrid symmetric -> full (warm start across variants)
# --------------------------------------------------------------------------
# Strategy: (1) the SYMMETRIC sweep (cheap, ~5 params/layer) finds a good starting
# point; (2) its solution is EXPANDED to per-bond parameters by copying each shared
# θ to every bond of its color class — the resulting quantum state is EXACTLY the
# same, only the parametrization changes (30 params/layer, now free);
# (3) the FULL HVA refines from there with L-BFGS + adjoint gradient. This buys the
# full variant's expressiveness at the cost of ONE full optimization (not the whole
# sweep).

def expand_symmetric_to_full(sim, x_sym, colors, ncol, reps):
    """
    Converts the symmetric vector (reps*ncol) to the full vector (reps*n_bonds) by
    copying each shared θ to every bond of its class. By construction,
    energy(x_full) == the symmetric energy at x_sym (same unitary, different
    parametrization).
    """
    npl = sim.n_params_per_layer
    x_full = np.empty(reps * npl)
    for r in range(reps):
        for k in range(npl):
            x_full[r * npl + k] = x_sym[r * ncol + colors[k]]
    return x_full


def refine_full_from_symmetric(sim, x_sym, reps, E_exact, psi_exact=None,
                               maxiter=300, verbose=True):
    """
    Hybrid phases (2)+(3): expands the `reps`-layer symmetric solution and refines
    with the full HVA (L-BFGS-B + adjoint gradient). Returns a dict with the starting
    point (start_*, which must match the symmetric result — consistency check) and
    the refined result (energy, err_pct, s2, fidelity, x, nit).
    """
    colors, ncol = edge_color_classes(sim.edges)
    x0 = expand_symmetric_to_full(sim, x_sym, colors, ncol, reps)
    e_start = sim.energy(x0, reps)
    if verbose:
        print(f"starting point (expanded symmetric, {len(x0)} params): "
              f"E={e_start:.3f}  err={abs(e_start-E_exact)/abs(E_exact)*100:.2f}%")
    res = minimize(lambda z: sim.energy_and_grad(z, reps), x0, jac=True,
                   method="L-BFGS-B", options={"maxiter": maxiter})
    sv = sim.statevector(res.x, reps)
    out = dict(reps=reps, n_params=len(x0),
               start_energy=float(e_start),
               start_err_pct=abs(e_start - E_exact) / abs(E_exact) * 100,
               energy=float(res.fun),
               err_pct=abs(res.fun - E_exact) / abs(E_exact) * 100,
               s2=sim.s2(sv),
               fidelity=(abs(np.vdot(psi_exact, sv))**2 if psi_exact is not None else np.nan),
               x=res.x, nit=int(res.nit))
    if verbose:
        fid = "" if psi_exact is None else f"  fid={out['fidelity']:.4f}"
        print(f"refined (full, {out['nit']} L-BFGS iters):           "
              f"E={out['energy']:.3f}  err={out['err_pct']:.2f}%  <S^2>={out['s2']:.4f}{fid}")
    return out


# --------------------------------------------------------------------------
# 8. Result persistence (the optima must NOT live only in the kernel)
# --------------------------------------------------------------------------
def save_sweep(results, path):
    """
    Saves a sweep (list of dicts with reps/x/energy/...) or a single result
    (dict, e.g. res_hyb — pass it as [res_hyb]) to an .npz file. This way the
    optimal parameter vectors survive kernel restarts.
    """
    import os
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    payload, meta = {}, []
    for r in results:
        reps = int(r["reps"])
        payload[f"x_{reps}"] = np.asarray(r["x"], dtype=float)
        meta.append([reps, len(np.atleast_1d(r["x"])), float(r["energy"]),
                     float(r.get("err_pct", np.nan)), float(r.get("s2", np.nan)),
                     float(r.get("fidelity", np.nan))])
    payload["meta"] = np.asarray(meta, dtype=float)
    np.savez(path, **payload)


def load_sweep(path):
    """Inverse of save_sweep: returns the list of dicts (reps, x, energy, err_pct, s2, fidelity)."""
    d = np.load(path)
    out = []
    for row in d["meta"]:
        reps = int(row[0])
        out.append(dict(reps=reps, n_params=int(row[1]), energy=float(row[2]),
                        err_pct=float(row[3]), s2=float(row[4]), fidelity=float(row[5]),
                        x=d[f"x_{reps}"]))
    return out


# --------------------------------------------------------------------------
# 9. Fine-grained analysis: spin-spin correlations and entanglement entropy
# --------------------------------------------------------------------------
def _apply2_sv(n, psi, G, a, b):
    """Applies a 4x4 matrix G to qubits (a,b) of a statevector reshaped to (2,)*n."""
    axa, axb = n - 1 - a, n - 1 - b
    psi = np.moveaxis(psi, [axa, axb], [0, 1])
    sh = psi.shape
    psi = (G @ psi.reshape(4, -1)).reshape(sh)
    return np.moveaxis(psi, [0, 1], [axa, axb])


def pair_correlations(n, sv, pairs):
    """
    Correlations ⟨S_i·S_j⟩ = ⟨X_iX_j+Y_iY_j+Z_iZ_j⟩/4 for each pair (i,j), computed
    term by term on the statevector (light: no global operators are built).
    Returns {(i,j): value}. Pure singlet: -3/4; uncorrelated: 0.
    """
    psiT = np.asarray(sv).reshape((2,) * n)
    out = {}
    for (i, j) in pairs:
        b = _apply2_sv(n, psiT.copy(), _BOND, i, j).reshape(-1)
        out[(i, j)] = float(np.real(np.vdot(np.asarray(sv).reshape(-1), b))) / 4.0
    return out


def entanglement_entropy_cuts(n, sv):
    """
    Von Neumann entropy S(k) (in bits) of the qubit block {0..k-1} for k = 1..n-1,
    via SVD of the reshaped statevector. A cut that splits a singlet contributes
    1 bit; a product state gives 0. Note: the "block {0..k-1}" refers to the tensor
    axes (Qiskit qubit order).
    """
    v = np.asarray(sv).reshape((2,) * n)
    ent = []
    for k in range(1, n):
        m = v.reshape(2 ** k, 2 ** (n - k))
        s = np.linalg.svd(m, compute_uv=False)
        p = s ** 2
        p = p[p > 1e-14]
        ent.append(float(-(p * np.log2(p)).sum()))
    return ent
